version: '3.8'

services:

  seshn-server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@seshn-db:5432/seshn_db_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@seshn-db:5432/sesh_db_test
      - AUTH0_CLIENT_ORIGIN=http://localhost:4040
      - AUTH0_DOMAIN=dev-xf5mji86.us.auth0.com
      - AUTH0_AUDIENCE=https://dev-xf5mji86.us.auth0.com/api/v2/
    depends_on:
      - seshn-db

  seshn-db:  # new
    build:
      context: ./src/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
